# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dosMic.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dosMic(object):
    def setupUi(self, dosMic):
        dosMic.setObjectName("dosMic")
        dosMic.resize(1104, 255)
        self.tableWidget = QtWidgets.QTableWidget(dosMic)
        self.tableWidget.setGeometry(QtCore.QRect(0, 60, 1101, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(21)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.lo = QtWidgets.QLabel(dosMic)
        self.lo.setGeometry(QtCore.QRect(10, 10, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lo.setFont(font)
        self.lo.setTextFormat(QtCore.Qt.AutoText)
        self.lo.setScaledContents(False)
        self.lo.setObjectName("lo")
        self.loo = QtWidgets.QLabel(dosMic)
        self.loo.setGeometry(QtCore.QRect(500, 20, 331, 16))
        self.loo.setObjectName("loo")
        self.dosMicAsignar = QtWidgets.QPushButton(dosMic)
        self.dosMicAsignar.setGeometry(QtCore.QRect(970, 10, 121, 41))
        self.dosMicAsignar.setObjectName("dosMicAsignar")
        self.tableWidget_2 = QtWidgets.QTableWidget(dosMic)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 160, 1101, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget_2.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(21)
        self.tableWidget_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(30)
        self.ExcelButton = QtWidgets.QPushButton(dosMic)
        self.ExcelButton.setGeometry(QtCore.QRect(840, 10, 121, 41))
        self.ExcelButton.setObjectName("ExcelButton")

        self.retranslateUi(dosMic)
        QtCore.QMetaObject.connectSlotsByName(dosMic)

    def retranslateUi(self, dosMic):
        _translate = QtCore.QCoreApplication.translate
        dosMic.setWindowTitle(_translate("dosMic", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("dosMic", "Mic 1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("dosMic", "Mic 1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("dosMic", "Fuente"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("dosMic", "50"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("dosMic", "63"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("dosMic", "80"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("dosMic", "100"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("dosMic", "125"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("dosMic", "160"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("dosMic", "200"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("dosMic", "315"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("dosMic", "215"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("dosMic", "400"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("dosMic", "500"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("dosMic", "630"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("dosMic", "800"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("dosMic", "1000"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("dosMic", "1250"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("dosMic", "1600"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("dosMic", "2000"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("dosMic", "2500"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("dosMic", "3150"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("dosMic", "4000"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("dosMic", "A"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("dosMic", "B"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.lo.setText(_translate("dosMic", "Introducir los valores de las mediciones para cada fuente:"))
        self.loo.setText(_translate("dosMic", "No olvides presionar \"Asignar\" una vez que los datos esten cargados!"))
        self.dosMicAsignar.setText(_translate("dosMic", "Asignar"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("dosMic", "Mic 2"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("dosMic", "Mic 2"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("dosMic", "Fuente"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("dosMic", "50"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("dosMic", "63"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("dosMic", "80"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("dosMic", "100"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("dosMic", "125"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("dosMic", "160"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("dosMic", "200"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("dosMic", "315"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("dosMic", "215"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("dosMic", "400"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("dosMic", "500"))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("dosMic", "630"))
        item = self.tableWidget_2.horizontalHeaderItem(13)
        item.setText(_translate("dosMic", "800"))
        item = self.tableWidget_2.horizontalHeaderItem(14)
        item.setText(_translate("dosMic", "1000"))
        item = self.tableWidget_2.horizontalHeaderItem(15)
        item.setText(_translate("dosMic", "1250"))
        item = self.tableWidget_2.horizontalHeaderItem(16)
        item.setText(_translate("dosMic", "1600"))
        item = self.tableWidget_2.horizontalHeaderItem(17)
        item.setText(_translate("dosMic", "2000"))
        item = self.tableWidget_2.horizontalHeaderItem(18)
        item.setText(_translate("dosMic", "2500"))
        item = self.tableWidget_2.horizontalHeaderItem(19)
        item.setText(_translate("dosMic", "3150"))
        item = self.tableWidget_2.horizontalHeaderItem(20)
        item.setText(_translate("dosMic", "4000"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("dosMic", "A"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("dosMic", "B"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.ExcelButton.setText(_translate("dosMic", "Excel"))

