# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unMic.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_unMic(object):
    def setupUi(self, unMic):
        unMic.setObjectName("unMic")
        unMic.resize(1104, 152)
        self.tableWidget = QtWidgets.QTableWidget(unMic)
        self.tableWidget.setGeometry(QtCore.QRect(0, 60, 1101, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(21)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.lo = QtWidgets.QLabel(unMic)
        self.lo.setGeometry(QtCore.QRect(10, 10, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lo.setFont(font)
        self.lo.setTextFormat(QtCore.Qt.AutoText)
        self.lo.setScaledContents(False)
        self.lo.setObjectName("lo")
        self.loo = QtWidgets.QLabel(unMic)
        self.loo.setGeometry(QtCore.QRect(500, 20, 331, 16))
        self.loo.setObjectName("loo")
        self.unMicAsignar = QtWidgets.QPushButton(unMic)
        self.unMicAsignar.setGeometry(QtCore.QRect(970, 10, 121, 41))
        self.unMicAsignar.setObjectName("unMicAsignar")
        self.ExcelButton = QtWidgets.QPushButton(unMic)
        self.ExcelButton.setGeometry(QtCore.QRect(840, 10, 121, 41))
        self.ExcelButton.setObjectName("ExcelButton")

        self.retranslateUi(unMic)
        QtCore.QMetaObject.connectSlotsByName(unMic)

    def retranslateUi(self, unMic):
        _translate = QtCore.QCoreApplication.translate
        unMic.setWindowTitle(_translate("unMic", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("unMic", "Mic 1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("unMic", "Mic 1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("unMic", "Fuente"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("unMic", "50"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("unMic", "63"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("unMic", "80"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("unMic", "100"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("unMic", "125"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("unMic", "160"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("unMic", "200"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("unMic", "315"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("unMic", "215"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("unMic", "400"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("unMic", "500"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("unMic", "630"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("unMic", "800"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("unMic", "1000"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("unMic", "1250"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("unMic", "1600"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("unMic", "2000"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("unMic", "2500"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("unMic", "3150"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("unMic", "4000"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("unMic", "A"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("unMic", "B"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.lo.setText(_translate("unMic", "Introducir los valores de las mediciones para cada fuente:"))
        self.loo.setText(_translate("unMic", "No olvides presionar \"Asignar\" una vez que los datos esten cargados!"))
        self.unMicAsignar.setText(_translate("unMic", "Asignar"))
        self.ExcelButton.setText(_translate("unMic", "Excel"))

